[host.se1_classic]
hostname = "se1.proof.cit.tum.de"
user = "cluster"
jobs = 2
threads = 8
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.se2_classic]
hostname = "se2.proof.cit.tum.de"
user = "cluster"
jobs = 3
threads = 8
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.se3_classic]
hostname = "se3.proof.cit.tum.de"
user = "cluster"
jobs = 3
threads = 8
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.se4_classic]
hostname = "se4.proof.cit.tum.de"
user = "cluster"
jobs = 3
threads = 8
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.of1-proof_classic]
hostname = "of1.proof.cit.tum.de"
user = "cluster"
jobs = 2
threads = 8
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.of2-proof_classic]
hostname = "of2.proof.cit.tum.de"
user = "cluster"
jobs = 2
threads = 8
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.of3-proof_classic]
hostname = "of3.proof.cit.tum.de"
user = "cluster"
jobs = 2
threads = 8
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.of4-proof_classic]
hostname = "of4.proof.cit.tum.de"
user = "cluster"
jobs = 2
threads = 8
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.se1_schedule]
hostname = "se1.proof.cit.tum.de"
user = "cluster"
jobs = 7
threads = 12
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.se2_schedule]
hostname = "se2.proof.cit.tum.de"
user = "cluster"
jobs = 8
threads = 16
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.se3_schedule]
hostname = "se3.proof.cit.tum.de"
user = "cluster"
jobs = 8
threads = 16
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.se4_schedule]
hostname = "se4.proof.cit.tum.de"
user = "cluster"
jobs = 8
threads = 16
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.of1-proof_schedule]
hostname = "of1.proof.cit.tum.de"
user = "cluster"
jobs = 4
threads = 16
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.of2-proof_schedule]
hostname = "of2.proof.cit.tum.de"
user = "cluster"
jobs = 4
threads = 16
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.of3-proof_schedule]
hostname = "of3.proof.cit.tum.de"
user = "cluster"
jobs = 4
threads = 16
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[host.of4-proof_schedule]
hostname = "of4.proof.cit.tum.de"
user = "cluster"
jobs = 4
threads = 16
settings = """
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/cakeml"
init_components "${ISABELLE_COMPONENTS_BASE:-$USER_HOME/.isabelle/contrib}" "$ISABELLE_HOME/Admin/components/optional"
ISABELLE_SWIPL=swipl
ISABELLE_SMLNJ=sml
ISABELLE_CC=gcc
ISABELLE_DOTNET_SETUP=true
ISABELLE_GHC_SETUP=true
ISABELLE_GO_SETUP=true
ISABELLE_OCAML_SETUP=true
ISABELLE_TOOL_JAVA_OPTIONS="$ISABELLE_TOOL_JAVA_OPTIONS -Xms4g -Xmx32G -XX:SoftMaxHeapSize=8g"
"""

[cluster.ls21-full]
hosts = [
  "of1-proof_classic",
  "of2-proof_classic",
  "of3-proof_classic",
  "of4-proof_classic",
  "se1_classic",
  "se2_classic",
  "se3_classic",
  "se4_classic",
  "of1-proof_schedule",
  "of2-proof_schedule",
  "of3-proof_schedule",
  "of4-proof_schedule",
  "se1_schedule",
  "se2_schedule",
  "se3_schedule",
  "se4_schedule",
]

[cluster.default]
hosts = [
  "of1-proof_classic",
  "of2-proof_classic",
  "of3-proof_classic",
  "of4-proof_classic",
  "se1_classic",
  "se2_classic",
  "se3_classic",
  "se4_classic",
]

[cluster.schedule]
hosts = [
  "of1-proof_schedule",
  "of2-proof_schedule",
  "of3-proof_schedule",
  "of4-proof_schedule",
  "se1_schedule",
  "se2_schedule",
  "se3_schedule",
  "se4_schedule",
]